version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: api_todo_list_bd_usuarios
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./bd/squema.sql:/docker-entrypoint-initdb.d/squema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ms_usuarios:
    build:
      context: ./ms
      dockerfile: Dockerfile
    container_name: api_todo_list_ms_usuarios
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "${MS_PORT}:${MS_PORT}"

