version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: api_todo_list_bd
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./bd/squema.sql:/docker-entrypoint-initdb.d/squema.sql
    restart: unless-stopped
