version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: api_todo_list_bd
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./squema.sql:/docker-entrypoint-initdb.d/squema.sql
    restart: unless-stopped
